### PR TITLE
Trustmark Entity Role

### PR DESCRIPTION
**Pull request by damikael**
## Title
 trustmark entity_role
  
## Content
Change the label 'entity_type' for trust mark with entity_role

## Review

- [X] Ensure your files are written following RST specs (*not MD!*)
- [X] Italian version
- [X] English version
- [ ] Example files 
- [X] Ask for review

### CODE REVIEW

**Comment by peppelinux** [comment]
In OIDC Federation we have the Entity Types, corresponding at the roles a participant may have in the federation.

Considering that every participant may issue TM, but only which are recognized by the TA should be considered valid, a federation entity may be a trust mark issuer

we don't have the role trustmark_entity_type in Federation 1.0

I'd use instead this PR to fix this typo, we define the role intermediary in the table, but federation_entity in the examples

image

and also:, for the english version the term Intermediary should be changed to Intermediate

**Comment by damikael** [comment]
So, can you confirm that the entity_type classification in trust mark
https://github.com/italia/spid-cie-oidc-docs/blame/versione-corrente/docs/en/trust_marks.rst#L73
should be equal to the classification of metadata
https://github.com/italia/spid-cie-oidc-docs/blame/versione-corrente/docs/en/entity_configuration.rst#L57

**Comment by peppelinux** [comment]
It's just a convention, if we say that that node in the path MUST be one of the possibile entity type we SHOULD use the entity type following the metadata types, considering that intermediary is not an entity type but a defined term in the specs

also: Intermediary should be changed in Intermediate, this is an english typo.

If AgID or IPZS wants use a custom id o change the patterns I'm ok with this, you have the power for do that, I just ask that both CIE and SPID uses the same pattern and possibily the same TM id. That would be great

**Comment by damikael** [comment]
For this reason, and for avoid ambiguity, I believe that it'is better to use in the description, a term other than entity_type. So I proposed trustmark_entity_type

**Comment by peppelinux** [comment]
A trust mark is issued to give additiona and administrave information about a participant, if it is a intermediate, RP, OP or AA.

What's the meaning and the achievent of having trustmark_entity_type? Considering that the TA publishes the "trust_mark_issuers" in its EC?

**Comment by peppelinux** [comment]
PS = the english typo related to the term Intermediate is fixed here: https://github.com/italia/spid-cie-oidc-docs/pull/157

**Comment by damikael** [comment]
Is the **entity_type** classification:

- openid_relying_party
- openid_provider
- federation_entity
- oauth_authorization_server
- oauth_resource

or:

- openid_relying_party
- openid_provider
- intermediate
- oauth_resource

? 

Maybe we could simply clarify that the type of the entities defined for trust mark are not strictly related to **entity_type** of metadata

**Comment by peppelinux** [comment]
I'm ok, we'll discuss it tomorrow :-)

**Review by fmarino-ipzs — APPROVED** [review]

**Review by peppelinux — APPROVED** [review]

**Pull request merged**
